<?php

namespace LaravelApiBuilder\Services;

use LaravelApiBuilder\Contracts\EndpointRepositoryContract;

/**
 * Generates OpenAPI 3.0 documentation from saved endpoint definitions.
 */
class SwaggerService
{
    public function __construct(private readonly EndpointRepositoryContract $endpoints)
    {
    }

    /**
     * @return array<string, mixed>
     */
    public function document(): array
    {
        $paths = [];

        foreach ($this->endpoints->active() as $endpoint) {
            $paths['/'.trim(config('api-builder.route_prefix', 'api'), '/').'/'.$endpoint->path][strtolower($endpoint->method)] = [
                'summary' => $endpoint->name,
                'description' => $endpoint->description,
                'security' => $endpoint->auth_required ? [['bearerAuth' => []]] : [],
                'responses' => [
                    '200' => [
                        'description' => 'Successful response generated by Laravel API Builder.',
                        'content' => [
                            'application/json' => [
                                'schema' => ['type' => 'object'],
                            ],
                        ],
                    ],
                ],
            ];
        }

        return [
            'openapi' => '3.0.3',
            'info' => [
                'title' => config('app.name', 'Laravel').' API Builder',
                'version' => '1.0.0',
            ],
            'paths' => $paths,
            'components' => [
                'securitySchemes' => [
                    'bearerAuth' => [
                        'type' => 'http',
                        'scheme' => 'bearer',
                    ],
                ],
            ],
        ];
    }
}
